version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/top-course-app
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: script/stop_container.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: script/start_container.sh
      timeout: 300
      runas: root