version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /top-course/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /top-course/docker-credentials/password
    DOCKER_REGISTRY_URL: /top-course/docker-registry/url

phases:
  install:
    runtime-versions:
      nodejs: 18.13.0
    commands:
      - echo Installing Node.js and npm
      - npm config set registry https://registry.npmjs.org/

  pre_build:
    commands:
      - echo Logging in to Docker Registry
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - IMAGE_REPO_NAME="top-course-app"
      - IMAGE_NAME="$DOCKER_REGISTRY_USERNAME/$IMAGE_REPO_NAME"

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image
      - docker build -t $IMAGE_NAME:latest .
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image
      - docker push $IMAGE_NAME:latest
      - echo Writing image definitions file
      - printf '[{"name":"top-course-container","imageUri":"%s"}]' $IMAGE_NAME:latest > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - '**/*'
  base-directory: '.'
  discard-paths: no
  exclude-paths:
    - 'node_modules/**/*'
    - '.git/**/*'
    - '.gitignore'
    - 'README.md'
    - 'package-lock.json'

