version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /top-course/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /top-course/docker-credentials/password
    DOCKER_REGISTRY_URL: /top-course/docker-registry/url

phases:
  install:
    runtime-versions:
      nodejs: 18.13.0
    commands:
      - echo Installing Node.js and npm
      - npm config set registry https://registry.npmjs.org/

  pre_build:
    commands:
      - echo Logging in to Docker Registry
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - IMAGE_REPO_NAME="top-course-app"
      - IMAGE_NAME="$DOCKER_REGISTRY_USERNAME/$IMAGE_REPO_NAME"

  build:
    commands:
      - echo Build started on `date`
      - echo Packaging application into a zip file
      - zip -r online-shop-app.zip * .[^.]* 
      - echo Building the Docker image
      - docker build -t $IMAGE_NAME:latest .
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_NAME:latest
      - echo Uploading zip file to S3 root location...
      - aws s3 cp online-shop-app.zip s3://hindol-top-course/top-course-app/
      - echo Writing image definitions file...
      - printf '{"ImageURI":"%s", "Port":8000}' $IMAGE_NAME:latest > imageDefinitions.json
      - cat imageDefinitions.json

artifacts:
  files:
    - '**/*'
  base-directory: '.'
  discard-paths: no
  exclude-patterns:
    - 'node_modules/**/*'
    - '.git/**/*'
    - '.gitignore'
    - 'README.md'
    - 'package-lock.json'
