kind: VerticalPodAutoscaler
apiVersion: autoscaling.k8s.io/v1

metadata:
  name: top-course-vpa
  namespace: top-course

spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: top-course-deployment

  updatePolicy:
    updateMode: "Auto"

